services:
  goobface:
    build: .
    image: goobface-app
    container_name: goobface-app-1
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    # No ports exposed locally - Nginx handles routing
    command: npm run dev -- --host
    networks:
      - web_gateway
    environment:
      - NODE_ENV=development

networks:
  web_gateway:
    external: true
